name: 'chazzpm'
description: Converts Jupyter Notebooks and Word Docs into Jekyll Blog Posts
author: Hamel Husain
inputs:
  BOOL_SAVE_MARKDOWN:
    description: Either 'true' or 'false'.  Whether or not to commit converted markdown files from notebooks and word documents into the _posts directory in your repo.  This is useful for debugging.
    required: false
    default: false
  SSH_DEPLOY_KEY:
    description: an ssh deploy key is required if BOOL_SAVE_MARKDOWN = 'true'
    required: false
branding:
  color: 'yellow'
  icon: 'bar-chart-2'
runs:
  using: 'docker'
  image: '_action_files/Dockerfile'
